name: tapg_analytics
version: 1.0.0
config-version: 2
profile: tapg_analytics
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  tapg_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: dynamic_table
      +snowflake_warehouse: tapg_wh
      +target_lag: '1 minutes'
