WITH PARAMS AS (
    SELECT
        '2000-01-01'::DATE AS START_DATE,
        '2030-12-31'::DATE AS END_DATE
),

DATE_RANGE AS (
    SELECT
        DATEADD(
            DAY,
            SEQ4(),
            START_DATE
        ) AS DATE_VALUE
    FROM PARAMS,
         TABLE(
             GENERATOR(
                 ROWCOUNT => 12000
             )
         )
),
dim_date as(

SELECT
    TO_NUMBER(TO_CHAR(DATE_VALUE, 'YYYYMMDD')) AS DATE_ID,
    DATE_VALUE AS DATE,

    YEAR(DATE_VALUE) AS YEAR,
    QUARTER(DATE_VALUE) AS QUARTER,
    MONTH(DATE_VALUE) AS MONTH,
    MONTHNAME(DATE_VALUE) AS MONTH_NAME,

    WEEKISO(DATE_VALUE) AS WEEK_NUMBER,
    YEAROFWEEKISO(DATE_VALUE) AS WEEK_YEAR,

    DAY(DATE_VALUE) AS DAY_OF_MONTH,
    DAYOFYEAR(DATE_VALUE) AS DAY_OF_YEAR,
    DAYOFWEEKISO(DATE_VALUE) AS DAY_OF_WEEK,
    DAYNAME(DATE_VALUE) AS DAY_NAME,

    DATE_TRUNC('WEEK', DATE_VALUE) AS WEEK_START_DATE,
    DATEADD(
        DAY,
        6,
        DATE_TRUNC('WEEK', DATE_VALUE)
    ) AS WEEK_END_DATE,

    DATE_TRUNC('MONTH', DATE_VALUE) AS MONTH_START_DATE,
    LAST_DAY(DATE_VALUE, 'MONTH') AS MONTH_END_DATE,

    DATE_TRUNC('QUARTER', DATE_VALUE) AS QUARTER_START_DATE,

    DATE_TRUNC('YEAR', DATE_VALUE) AS YEAR_START_DATE,

    CASE
        WHEN DAYOFWEEKISO(DATE_VALUE) IN (6,7)
        THEN TRUE
        ELSE FALSE
    END AS IS_WEEKEND

FROM DATE_RANGE, PARAMS
WHERE DATE_VALUE <= PARAMS.END_DATE
ORDER BY DATE_VALUE
)

SELECT * FROM dim_date