--- Create Warehouse ---
CREATE OR REPLACE WAREHOUSE TAPG_WH;

--- Create Database ---
CREATE OR REPLACE DATABASE TAPG_DB;

--- Create Schema ---
CREATE OR REPLACE SCHEMA TAPG_DB.TAPG_SCHEMA;

--- Create STAGE ---
CREATE OR REPLACE STAGE TAPG_DB.PUBLIC.TAPG_STAGE;

--- Create Tables Customers---
CREATE OR REPLACE TABLE TAPG_DB.TAPG_SCHEMA.CUSTOMERS (
	CUSTOMER_ID VARCHAR,
	CUSTOMER_UNIQUE_ID VARCHAR,
	CUSTOMER_ZIP_CODE_PREFIX VARCHAR,
	CUSTOMER_CITY VARCHAR,
	CUSTOMER_STATE VARCHAR
);

--- Create Tables Orders---
CREATE OR REPLACE TABLE TAPG_DB.TAPG_SCHEMA.ORDERS (
	ORDER_ID VARCHAR,
	CUSTOMER_ID VARCHAR,
	ORDER_STATUS VARCHAR,
	ORDER_PURCHASE_TIMESTAMP TIMESTAMP_NTZ,
	ORDER_APPROVED_AT TIMESTAMP_NTZ,
	ORDER_DELIVERED_CARRIER_DATE TIMESTAMP_NTZ,
	ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP_NTZ,
	ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP_NTZ
);

--- Create Tables Order Items---
CREATE OR REPLACE TABLE TAPG_DB.TAPG_SCHEMA.ORDER_ITEMS (
	ORDER_ID VARCHAR,
	ORDER_ITEM_ID NUMBER,
	PRODUCT_ID VARCHAR,
	SELLER_ID VARCHAR,
	SHIPPING_LIMIT_DATE TIMESTAMP_NTZ,
	PRICE NUMBER,
	FREIGHT_VALUE NUMBER
);

--- Create Tables Payments---
CREATE OR REPLACE TABLE TAPG_DB.TAPG_SCHEMA.PAYMENTS (
	ORDER_ID VARCHAR,
	PAYMENT_SEQUENTIAL NUMBER,
	PAYMENT_TYPE VARCHAR,
	PAYMENT_INSTALLMENTS NUMBER,
	PAYMENT_VALUE NUMBER
);

--- Create Tables Products---
CREATE OR REPLACE TABLE TAPG_DB.TAPG_SCHEMA.PRODUCTS (
	PRODUCT_ID VARCHAR,
	PRODUCT_CATEGORY_NAME VARCHAR,
	PRODUCT_NAME_LENGHT NUMBER,
	PRODUCT_DESCRIPTION_LENGHT NUMBER,
	PRODUCT_PHOTOS_QTY NUMBER,
	PRODUCT_WEIGHT_G NUMBER,
	PRODUCT_LENGTH_CM NUMBER,
	PRODUCT_HEIGHT_CM NUMBER,
	PRODUCT_WIDTH_CM NUMBER
);